Fix building with GCC 10
When trying to build with gcc 10, there is a linker error:

    /usr/bin/ld: /tmp/ccjRQbpX.o:/builddir/build/BUILD/entr-4.4/data.h:33: multiple definition of `files'; /tmp/ccHpowMW.o:/builddir/build/BUILD/entr-4.4/missing/../data.h:33: first defined here
    collect2: error: ld returned 1 exit status

This is a known thing in gcc 10:

https://gcc.gnu.org/gcc-10/porting_to.html#common

This patch adds extern keyword to the header file and removes it from
exactly one source file.